name: Unittests

on:
  # Allow to trigger the workflow manually (e.g. when deps changes)
  workflow_dispatch:
  # Run on pushes to main or test branches
  push:
    branches:
      - main
  # Run on pull requests to main
  pull_request:
    branches:
      - main

jobs:
  unittest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v3

    # Install deps
    - uses: actions/setup-python@v4
      with:
        python-version: 3.10.14
        # Uncomment to cache of pip dependencies (if tests too slow)
        # cache: pip
        # cache-dependency-path: '**/pyproject.toml'

    - run: pip --version
    - run: pip install -e .[dev,test]
    - run: pip freeze

    # Run tests
    - name: Run tests
      run: python run_tests.py