ARG PYTHON_VERSION=3.10.5
FROM python:${PYTHON_VERSION} as base

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

COPY . .
EXPOSE 8000
CMD uvicorn main:app --reload --host 0.0.0.0 --port 8000