from dotenv import load_dotenv
import os

load_dotenv('.env')

class Settings:
    DATABASE_URL = os.getenv("DATABASE_URL")
    SECRET_KEY = os.getenv("SECRET_KEY")
    SECRET_KEY = os.getenv("SECRET_KEY")
    ALGORITHM = os.getenv("JWT_ALGORITHM")
    ACCESS_TOKEN_EXPIRE_MINUTES = os.getenv("AT_EXPIRE_MINUTES")
    REFRESH_TOKEN_EXPIRE_DAYS = os.getenv("RT_EXPIRE_DAYS")
    OAUTH2_SECRET = os.getenv("OAUTH2_SECRET")
    GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
    FRONT_END_URL = os.getenv("FRONT_END_URL")
    SENDGRID_API_KEY = os.getenv("SENDGRID_API_KEY")
    SENDGRID_FROM_EMAIL = os.getenv("SENDGRID_FROM_EMAIL")
    SENDGRID_WELCOME_TEMPLATE_ID = os.getenv("SENDGRID_WELCOME_TEMPLATE_ID")
    SENDGRID_EMAIL_VERIFICATION_TEMPLATE_ID = os.getenv("SENDGRID_EMAIL_VERIFICATION_TEMPLATE_ID")
    SENDGRID_PASSWORD_RESET_TEMPLATE_ID = os.getenv("SENDGRID_PASSWORD_RESET_TEMPLATE_ID")