artifacts_root : artifacts

data_ingestion:
  root_dir : artifacts/data_ingestion 
  source_URL: https://github.com/ozkanvitamu/personal_projects/blob/main/Datasets/wine_quality.zip
  local_data_file: artifacts/data_ingestion/wine_quality.zip
  unzip_dir: artifacts/data_ingestion