version: '3'

includes:
  docker:
    taskfile: ./DockerTasks.yml

  kubernetes:
    taskfile: ./KubernetesTasks.yml
  
  helm:  
    taskfile: ./HelmTasks.yml
  
  systemd:
    taskfile: ./SystemdTasks.yml
  
  other:
    taskfile: ./OtherTasks.yml

dotenv:
  - './.env'